select * from mytable;

#Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as Revenue from mytable group by gender; 

#Q2. Which customers used a discount but still spent more than the average purchase
select customer_id,purchase_amount from mytable 
where discount_applied="yes" and purchase_amount >= (select avg(purchase_amount) from mytable);

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as Avgrage_rating from mytable
group by item_purchased
order by Avgrage_rating desc limit 5; 

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) from mytable
where shipping_type in ('Express','Standard')
group by shipping_type;
#Q5. Do subscribed customers spend more? Compare average spend and 
#total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as Total_cus,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as Total_revenue from mytable
group by subscription_status
order by total_revenue,avg_spend desc;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM mytable
group by item_purchased
order by discount_rate desc limit 5;
 
#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM mytable
)
SELECT 
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;

#Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts where item_rank <=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers from mytable
where previous_purchases > 5
group by subscription_status;

-#Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue from mytable
group by age_group
order by total_revenue desc;